### ISSUE TITLE
Missing Lyrics

### ISSUE THREAD

**Issue by Flickino** [ziruiLiu-g/spotify-floating-lyrics#1]
Hello, i dont know what i did wrong but when it boots, i see only picture and name of the song, nothing more, i dont have clue how to fix it.
![image_2023-09-30_154556568](https://github.com/ziruiLiu-g/spotify-floating-lyrics/assets/124439197/a2ebf1ba-3ce2-46e7-a1d4-0132e51025ac)

**Comment by raphaelgomez360** [comment]
@Flickino did you ever fix this ?

**Comment by ziruiLiu-g** [comment]
Hey guys, the lyric api seems like broken.
I will looking for  other solutions or trying to implement my own version.
This gonna take a while. If u have portable solution please feel free to raise PR

**Comment by raphaelgomez360** [comment]
Thanks @ziruiLiu-g ! 

I'm not very C++ fluent so not sure i'll get adventurous enough to PR, but from a quick investigation:

## spotify-lyrics-api 

It seems that the initial deployment you were using in `lib/http/logic/request/spotify_herokuapp_request.dart` was using `spotify-lyric-api.herokuapp.com` as authority. 

This API address is indeed down, but this one is up and running: `https://spotify-lyric-api-984e7b4face0.herokuapp.com/`

Do you think we could try just changing the endpoint ? 

Cheers !

**Comment by ziruiLiu-g** [comment]
hi @raphaelgomez360 @Flickino  I have replace the api.
It does work! 
Thanks for your contribution to this!!!

The new patch could be now downloaded

**Comment by ziruiLiu-g** [comment]
hi @raphaelgomez360 @Flickino
Looks like the replaced Api is also broken.
I have implemented native api call to fetch lyrics in the App. 
I have also updated the README to give more instructions on how to set up for the new release.

Feel free to download the latest version and try. 
And I am more than happy to get feedback from you guys, thanks!
