### ISSUE TITLE
Mobile Development

### ISSUE THREAD

**Issue by andredequeiroz** [ziruiLiu-g/spotify-floating-lyrics#2]
Hello!
Is there a chance in developing this to mobile?? Like a widget or something that overlay on display?? (my android calculator does that lol).

THank you!
You're a genius!

**Comment by ziruiLiu-g** [comment]
Hi Andre
I am afraid this could not be transferred into mobile version directly since I use some components which are specific for PC. 
BUT u definitely can try build and deploy the current version to mobile and see what needs to be replaced, if u r interested!!!
